# -*- coding: utf-8 -*-
"""quantization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsTqCAd-eXZfh6qFkhSh8BORFJQ7u7oL
"""

!pip install autoawq datasets transformers

import torch
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer
from datasets import load_dataset

# 1. Configuration
model_path = "mistralai/Mistral-7B-v0.3"
quant_path = "Mistral-7B-v0.3-AWQ-4bit-Wikitext"
quant_config = {
    "zero_point": True,
    "q_group_size": 128,
    "w_bit": 4,
    "version": "GEMM" # GEMM is better for general use/vLLM
}

# 2. Load Model & Tokenizer to GPU
# device_map="cuda:0" forces the model onto your first GPU
print("📦 Loading model to GPU...")
model = AutoAWQForCausalLM.from_pretrained(
    model_path,
    low_cpu_mem_usage=True,
    use_cache = False
    #device_map="auto",
    #torch_dtype=torch.float16
)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

# 3. Load & Format WikiText-2 Calibration Data
traindata = load_dataset('wikitext', 'wikitext-2-raw-v1', split='train')
# Filter for meaningful text blocks
calib_data = [text for text in traindata['text'] if len(text) > 128][:128]

# 4. Execute Quantization
# AutoAWQ uses the GPU kernels to calculate scales based on calib_data
print("🚀 Starting GPU-accelerated quantization...")
model.quantize(
    tokenizer,
    quant_config=quant_config,
    calib_data=calib_data,
    n_parallel_calib_samples = 32
)

# 5. Save the Quantized Model
model.save_quantized(quant_path)
tokenizer.save_pretrained(quant_path)

print(f"✅ GPU Quantization Complete! Saved to: {quant_path}")

drive_model_folder = "Mistral-7B-v0.3-AWQ-4bit-Wikitext"
model_path = f"/content/drive/My Drive/{drive_model_folder}"

# 3. Verify the path exists and list files
if os.path.exists(model_path):
    print(f"✅ Model found at: {model_path}")
    print("Files in directory:", os.listdir(model_path))
else:
    print(f"❌ Error: Could not find the folder at {model_path}")
    print("Please check your Google Drive folder name and structure.")