# -*- coding: utf-8 -*-
"""AWQ-Block.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zLi7uC1SM1ddjNxvu5wBW_KRLO_Ay8Pd
"""

!pip install autoawq datasets transformers

import torch
import torch.nn as nn
from awq.quantize.scale import apply_scale
import copy

# --- 1. MOCK QUANTIZER
class MockAWQQuantizer:
    def __init__(self, w_bit=4, group_size=128, zero_point=True):
        self.w_bit = w_bit
        self.group_size = group_size
        self.zero_point = zero_point

    def pseudo_quantize_tensor(self, w):
        """Standard 4-bit group-wise simulation logic"""
        org_w_shape = w.shape
        if self.group_size > 0:
            w = w.reshape(-1, self.group_size)

        # Calculate scaling factor (Max Absolute)
        max_val = w.abs().max(dim=-1, keepdim=True)[0]
        max_val = max_val.clamp(min=1e-5)

        # 4-bit range: -8 to 7
        q_max = 2**(self.w_bit-1) - 1
        q_min = -2**(self.w_bit-1)
        scales = max_val / q_max

        # Quantize and Dequantize
        q_w = torch.clamp(torch.round(w / scales), q_min, q_max)
        w = q_w * scales

        return w.reshape(org_w_shape)

def evaluate_quantization(org_block, quant_block, input_feat):
    org_block.eval()
    quant_block.eval()

    with torch.no_grad():
        # GROUND TRUTH
        reference_out = org_block(input_feat)
        # QUANTIZED RESULT
        quantized_out = quant_block(input_feat)

    # Calculate MSE
    mse = torch.mean((reference_out - quantized_out)**2).item()

    # Calculate SNR (Signal-to-Noise Ratio)
    # This tells you how much 'signal' survived vs the quantization 'noise'
    signal_power = torch.mean(reference_out**2).item()
    snr = 10 * torch.log10(torch.tensor(signal_power / mse)).item()

    print(f"\n--- 📈 Quantization Report ---")
    print(f"MSE Loss: {mse:.8f}")
    print(f"Signal-to-Noise Ratio: {snr:.2f} dB")
    return snr

# --- 2. SETUP THE MINI-BLOCK ---
class AWQMiniBlock(nn.Module):
    def __init__(self, dim=1024):
        super().__init__()
        self.ln = nn.LayerNorm(dim)
        self.linear = nn.Linear(dim, dim, bias=False)

    def forward(self, x):
        return self.linear(self.ln(x))

block = AWQMiniBlock(1024).cuda().half()
original_block_fp16 = copy.deepcopy(block)
input_feat = torch.randn(1, 128, 1024).cuda().half()
input_feat[:, :, :10] *= 10.0 # Artificial Outliers

# --- 3. FULL AWQ SEARCH & ABSORPTION ---
def run_baseline_awq(block, input_feat):
    # Get ground truth output
    with torch.no_grad():
        x_after_ln = block.ln(input_feat).view(-1, input_feat.shape[-1])
        org_output = block.linear(block.ln(input_feat))

    # AWQ Grid Search params
    n_grid = 20
    best_error = float('inf')
    best_scales = None

    # Pre-calculate stats for the AWQ formula: s = x_max^alpha / w_max^(1-alpha)
    x_max = x_after_ln.abs().mean(0)
    w_max = block.linear.weight.data.abs().max(dim=0)[0]
    quantizer = MockAWQQuantizer(w_bit=4, group_size=128)

    print("🔍 Searching for best alpha...")
    for i in range(n_grid):
        alpha = i / n_grid
        scales = x_max.pow(alpha) / w_max.pow(1 - alpha)
        scales = scales.clamp(min=1e-4).view(-1)

        # Apply scaling to weight (for error testing)
        W_test = block.linear.weight.data * scales.view(1, -1)
        W_test_q = quantizer.pseudo_quantize_tensor(W_test)
        W_test_q /= scales.view(1, -1) # Undo scale for comparison

        # Calculate MSE loss on activations
        test_output = x_after_ln @ W_test_q.t()
        loss = (org_output.view(-1, 1024) - test_output).pow(2).mean().item()

        if loss < best_error:
            best_error = loss
            best_scales = scales
            print(f"  Alpha: {alpha:.2f} | MSE Loss: {loss:.6f}")

    # --- ABSORPTION STEP ---
    # We use AutoAWQ's official apply_scale for the baseline comparison
    scales_list = [('ln', ['linear'], best_scales)]
    apply_scale(block, scales_list)

    # Final quantization of the weight
    block.linear.weight.data = quantizer.pseudo_quantize_tensor(block.linear.weight.data)

    print("✅ Baseline AWQ search and absorption complete.")
    return block

# Run the baseline
baseline_block = run_baseline_awq(block, input_feat)

# Execute comparison
baseline_block = baseline_block.cuda().half() # Ensure baseline_block is on CUDA and half precision
evaluate_quantization(original_block_fp16, baseline_block, input_feat)